config/routes.rb
JoesBooks::Application.routes.draw do
  get "static_pages/home"

  get "static_pages/admin_home"

  get "static_pages/help"

  get "all_votes/complete_round"
  get "all_votes/winner"
  resources :all_votes

  get "user/update"

  get "all_books/index"
  resources :all_books

  devise_for :users, :path => 'accounts'

  resources :users do
    resources :books
    resources :votes
  end

  resources :comments

  resources :books

  root :to => 'books#index'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def admin_home
  end

  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/admin_home.html.erb
<h1>Admin Landing Page</h1>

<%= link_to 'Start a New Election', new_all_vote_path, data: { confirm: 'Are you sure? This will delete all current votes.' }, class: "btn btn-large btn-primary" %></p>
<%= link_to 'Complete a Voting Round', all_votes_complete_round_path, data: { confirm: 'Are you sure? This will reset all current votes, and advance to the next round.' }, class: "btn btn-large btn-primary" %></p>
<%= link_to 'Send Email Reminder to Non-Voters', static_pages_admin_home_path, class: "btn btn-large btn-primary" %></p>
<%= link_to 'Compose Message to All Users', static_pages_admin_home_path, class: "btn btn-large btn-primary" %>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>