config/routes.rb
JoesBooks::Application.routes.draw do
  get "static_pages/home"

  get "static_pages/admin_home"

  get "static_pages/help"

  get "all_votes/complete_round"
  get "all_votes/winner"
  resources :all_votes

  get "user/update"

  get "all_books/index"
  resources :all_books

  devise_for :users, :path => 'accounts'

  resources :users do
    resources :books
    resources :votes
  end

  resources :comments

  resources :books

  root :to => 'books#index'

end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  author      :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#  votes_count :integer          default(0), not null
#  asin        :string(255)
#

class Book < ActiveRecord::Base
  attr_accessible :author, :title, :asin, :user_id

  validates :author, :title, :presence => true
  validates_uniqueness_of :title, :case_sensitive => false

  belongs_to :user	
  has_many :votes
  has_many :comments
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  require 'vacuum'
  require "rexml/document"
  # include REXML

  before_filter :authenticate_user!

  def index
    @books = Book.where(user_id: current_user)
  end

  def show
    @book = Book.find(params[:id])
    @comments = @book.comments
    @comment = Comment.new(:book_id => params[:id])
    # @comment = Comment.new(params[:id])
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(params[:book])
    @book.user_id = current_user.id
    if @book.asin.blank?  # if current_user didn't enter an ASIN, then look it up
      @book.asin = get_book_asin(@book.title + " " + @book.author) 
    end

    if @book.save
      redirect_to [current_user, @book], notice: 'Book was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @book = Book.find(params[:id])

    if @book.update_attributes(params[:book])
      redirect_to [current_user, @book], notice: 'Book was successfully updated.' 
    else
      render action: "edit" 
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to user_books_url 
  end

  def get_book_asin(keywords)
    req = Vacuum.new
    req.configure key:    ENV['AWS_KEY'],
                  secret: ENV['AWS_SECRET'],
                  tag:    ENV['AWS_TAG']

    res = req.get query: { 'Operation'   => 'ItemSearch',
                           'SearchIndex' => 'Books',
                           'Keywords'    => keywords }

    # do this to avoid using 'include REXML' above and running into Comment class name clash documented in 
    # https://groups.google.com/forum/?hl=en&fromgroups=#!topic/rubyonrails-talk/7RcK66ML_Xo
    doc = REXML::Document.new(res.body)
    detailPageURL = XPath.first(doc, "//DetailPageURL") 
    return /(.*ASIN%3D)(.*$)/.match(detailPageURL.text)[2]
  end
end

app/helpers/books_helper.rb
module BooksHelper
	def get_amazon_link(title, author)
		# "http://rcm.amazon.com/e/cm?lt1=_blank&bc1=FFFFFF&IS1=1&npa=1&bg1=FFFFFF&fc1=000000&lc1=0000FF&t=booclu00-20&o=1&p=8&l=as1&m=amazon&f=ifr&ref=qf_sp_asin_til&asins=1613821530"
		#{ }"book link for #{title} by #{author}"
		searchterms = title.split
		searchterms << "by"
		searchterms << author.split
		searchterms = searchterms.join("+").downcase
		"http://www.amazon.com/s/ref=nb_sb_noss_1?url=search-alias%3Daps&field-keywords=#{searchterms}&linkCode=xm2&tag=booclu00-20"
	end

	def amazon_pic_url(asin)
#		'<a href="http://www.amazon.com/gp/product/' + asin + '/ref=as_li_tf_il?ie=UTF8&camp=1789&creative=9325&creativeASIN=' + asin + '&linkCode=as2&tag=booclu00-20"><img border="0" src="http://ws.assoc-amazon.com/widgets/q?_encoding=UTF8&ASIN=' + asin + '&Format=_SL110_&ID=AsinImage&MarketPlace=US&ServiceVersion=20070822&WS=1&tag=booclu00-20" ></a><img src="http://www.assoc-amazon.com/e/ir?t=booclu00-20&l=as2&o=1&a=' + asin + '" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />'
	
		'<a href="http://www.amazon.com/gp/product/' + asin + '/ref=as_li_tf_il?ie=UTF8&camp=1789&creative=9325&creativeASIN=' + asin + '&linkCode=as2&tag=booclu00-20"><img border="0" src="http://ws.assoc-amazon.com/widgets/q?_encoding=UTF8&ASIN=' + asin + '&Format=_SL110_&ID=AsinImage&MarketPlace=US&ServiceVersion=20070822&WS=1&tag=booclu00-20" ></a><img src="http://www.assoc-amazon.com/e/ir?t=booclu00-20&l=as2&o=1&a=' + asin + '" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />'

	end


end

app/views/books/_form.html.erb
<%= form_for [current_user, @book] do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :ASIN %><br />
    <%= f.text_field :asin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/index.html.erb
<h1>My Book List</h1>
</br>

<table class="table table-striped table-condensed">
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Amazon Link</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% if @books.count.zero? %>
  <p><center>You do not currently have any books.  To add some, click New Book below.</center></p></br>
<% end %>

<% @books.each do |book| %>
  <tr>
    <td><%= link_to book.title, user_book_path(current_user, book) %></td>
    <td><%= book.author %></td>
    <td><%= link_to  raw(amazon_pic_url(book.asin)) %>
    <td><%= link_to 'Edit', edit_user_book_path(current_user, book) %></td>
    <td><%= link_to 'Remove', [current_user, book], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book', new_user_book_path(current_user), class: "btn btn-large btn-primary" %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', user_books_path %>

app/views/books/show.html.erb
<p>
  <b>Title:</b>
  <%= @book.title %>
</p>

<p>
  <b>Author:</b>
  <%= @book.author %>
</p>

<p>
  <b>Amazon link:</b>
  <%= link_to raw(amazon_pic_url(@book.asin)) %>
</p>


<%= link_to 'Edit', edit_user_book_path(current_user, @book.id) %> |
<%= link_to 'Back', user_books_path %> 

<%= form_for @comment do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :text, placeholder: "Compose new comment here ..." %>
    <%= f.hidden_field :book_id, :value => @book.id %>
  </div> 

  <div class="actions">
    <%= f.submit "Post Comment", class: "btn btn-large btn-primary" %>
  </div>
<% end %>

<h1>Comments for this Book:</h1>
</br>
<% @comments.each do |comment| %>
  <%= render partial: 'shared/comments', locals: {comment: comment} %>
<% end %>
<p id='current_user_id' style='display:none;'><%=current_user.email%></p>
<p></p>