config/routes.rb
JoesBooks::Application.routes.draw do
  get "static_pages/home"

  get "static_pages/admin_home"

  get "static_pages/help"

  get "all_votes/complete_round"
  get "all_votes/winner"
  resources :all_votes

  get "user/update"

  get "all_books/index"
  resources :all_books

  devise_for :users, :path => 'accounts'

  resources :users do
    resources :books
    resources :votes
  end

  resources :comments

  resources :books

  root :to => 'books#index'

end

app/models/vote.rb
# == Schema Information
#
# Table name: votes
#
#  id         :integer          not null, primary key
#  book_id    :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Vote < ActiveRecord::Base
  attr_accessible :book_id, :user_id

  validates :book_id, :user_id, :presence => true
  
  belongs_to :user
  belongs_to :book, :counter_cache => true
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @votes = Vote.all
  end

  def show
    @vote = Vote.find(params[:id])
  end

  def new
    @vote = Vote.new
    @vote.user_id = current_user.id

    # assign @books depending on state of election
    if (ConfigParameter.find_by_name("second_round_started").value == "false" )
      @books = Book.all
    else
      # if second round of voting has started, books are a subset of Book.all:
      # - don't include books that got no votes
      # - take at least half of the number of existing books as before
      @books = Book.all.select {|book| book.votes.count > 0}
    end
  end

  def edit
    @vote = Vote.find(params[:id])
  end

  def create
    @vote = Vote.new(params[:vote])

    if @vote.save
      # flash message below?
      flash[:notice] = "Vote was successfully cast!"
      redirect_to @vote, notice: 'Vote was successfully cast.'
    else
      render action: "new" 
    end
  end

  def update
    @vote = Vote.find(params[:id])

    if @vote.update_attributes(params[:vote])
      redirect_to @vote, notice: 'Vote was successfully updated.' 
    else
      render action: "edit"
    end
  end

  def destroy
    @vote = Vote.find(params[:id])
    @vote.destroy
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_form.html.erb
<%= form_for [current_user, @vote] do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :book_id %><br />
    <%= f.number_field :book_id %>
  </div>
  <!-- <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<h1>Listing votes</h1>

<table>
  <tr>
    <th>Book</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @votes.each do |vote| %>
  <tr>
    <td><%= vote.book_id %></td>
    <td><%= vote.user_id %></td>
    <td><%= link_to 'Show', vote %></td>
    <td><%= link_to 'Edit', edit_user_vote_path(vote) %></td>
    <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vote', new_user_vote_path %>

app/views/votes/new.html.erb
<h1>Voting Form</h1></br>

<%= form_for [current_user] do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table table-striped table-condensed">
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Amazon link</th>
    <th>Suggested By</th>
		<th>Vote</th> 
		<th></th>
  </tr>

	<% @books.each do |book| %>
	  <tr>
	    <td><%= book.title %></td>
	    <td><%= book.author %></td>
	    <td><%= link_to  raw(amazon_pic_url(book.asin)) %>
	    <td><%= User.find_by_id(book.user_id).first_name %></td>
	    <td>
	    <div class="field">
         <%= check_box_tag :voted_book_ids, book.id, current_user.voted_books.include?(book), :name => 'user[voted_book_ids][]' -%>
  		</div>
			</td> 
	  </tr>
	<% end %>
	</table>

	<br />

  <div class="actions">
    <%= f.submit "Submit my Vote" %>
  </div>
<% end %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Book:</b>
  <%= @vote.book_id %>
</p>

<p>
  <b>User:</b>
  <%= @vote.user_id %>
</p>


<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>