config/routes.rb
JoesBooks::Application.routes.draw do
  get "static_pages/home"

  get "static_pages/admin_home"

  get "static_pages/help"

  get "all_votes/complete_round"
  get "all_votes/winner"
  resources :all_votes

  get "user/update"

  get "all_books/index"
  resources :all_books

  devise_for :users, :path => 'accounts'

  resources :users do
    resources :books
    resources :votes
  end

  resources :comments

  resources :books

  root :to => 'books#index'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <% if user_signed_in? %>
      Signed in as user <%= current_user.email %>
    <% end %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://nytimes.com/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "joe\'s books", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li><%= link_to 'Home', user_books_path(current_user) %></li>
            <li><%= link_to 'Vote', new_user_vote_path(current_user) %></li>
            <li><%= link_to 'All books', all_books_index_path %></li>
            <li><%= link_to 'All votes', all_votes_path %></li>
            <% if current_user.admin? %>
              <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Admin <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Start a New Election', new_all_vote_path, data: { confirm: 'Are you sure? This will delete all current votes.' } %></li>
                <li><%= link_to 'Complete a Voting Round', all_votes_complete_round_path, data: { confirm: 'Are you sure? This will reset all current votes, and advance to the next round.' } %></li>
                <li><%= link_to 'Send Email Reminder to Non-Voters', '#' %></li>
                <li><%= link_to 'Compose Message to All Users', '#' %></li>
              </ul>
            </li>
            <% end %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                My Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    "application", media: "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	  <%= render 'layouts/shim' %>
	</head>

	<body>
		<%= render 'layouts/header' %>
		<div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
	</body>
</html>